[colors.normal]
black = "#000000"
red = "#00aa33"
green = "#00aa33"
yellow = "#00aa33"
blue = "#00aa33"
magenta = "#00aa33"
cyan = "#00aa33"
white = "#00aa33"

[colors.bright]
black = "#00aa33"
red = "#00aa33"
green = "#00aa33"
yellow = "#00aa33"
blue = "#00aa33"
magenta = "#00aa33"
cyan = "#00aa33"
white = "#00aa33"

[colors.cursor]
text = "#000000"
cursor = "#00aa33"

[colors.selection]
text = "#000000"
background = "#00aa33"

[colors.primary]
background = "#000000"
foreground = "#00aa33"

[[colors.indexed_colors]]
index = 16
color = "#00aa33"

[[colors.indexed_colors]]
index = 17
color = "#00aa33"
