vim.keymap.set("n", "<leader>gs", ":Git<cr>", { desc = "Git: status", silent = true })
vim.keymap.set("n", "<leader>ga", ":Gwrite<cr>", { desc = "Git: add current file", silent = true })
vim.keymap.set("n", "<leader>gaa", ":Git add .<cr>", { desc = "Git: add all files", silent = true })
vim.keymap.set("n", "<leader>gc", ":Git commit<cr>", { desc = "Git: commit" })
vim.keymap.set("n", "<leader>gp", ":Git push<cr>", { desc = "Git: push", silent = true })
vim.keymap.set("n", "<leader>gd", ":Gdiffsplit<cr>", { desc = "Git: diff", silent = true })
